feat: install hotjar tracking code
kiva/ui pull request #4048
Opened 2022-07-21 20:18 UTC by christian14b

This pr installs the code for Hotjar as an effort to understand how users are reacting to site's elements.

**Hotjar** is a third-party tool that allows internal users to survey visitors to the site based on various targeting measures.

2022-07-21 20:27 UTC, dyersituations commented
General question: why do we need hotjar if we already have fullstory?

2022-07-22 15:18 UTC, eddieferrer commented
+1 to Caseys question. So much tracking.... 

@mcstover do we need to mirror this script load for the unbounce pages that are wrapped in the IFrameEmbed? That script is currently in unbounce. It might be better going forward to move that script to the UI repo and have it available externally and then just load it in unbounce. This would make it easier to keep in sync with changes to `src/head/script.js`

2022-07-22 15:25 UTC, mcstover requested changes
This took needs a data audit, external configuration and potentially the addition of several data exclusion classes before being activated on the site.

2022-08-17 16:14 UTC, mcstover approved these changes
We've _now_ configured the HotJar account to "Suppress all on page content". Should this configuration change we will need to turn off the tool and alter our code to continue suppression of PII on the site.

2022-08-17 16:18 UTC, mcstover commented on config/audit.js
> +		hotjarId: '3071239',
@christian14b @emuvente I think we should at minimum setup a 2nd site that can be used across all lower environments for testing. I'll check our account for that option.

2022-08-18 17:13 UTC, mcstover approved these changes

2022-08-25 18:19 UTC, emuvente approved these changes
👍

2022-08-25 18:22 UTC, merged