feat: quick filters tracking + update
kiva/ui pull request #4277
Opened 2022-10-14 16:31 UTC by egoroza

adds tracking to quick filters experiment. also fixes a bug where livestock is not using flss query by adding its activityId to the query map.

2022-10-14 16:42 UTC, roger-in-kiva commented
Add the condition for livestock category here pls https://github.com/kiva/ui/blob/e47223fd6616c0b5ecff787f32c9df72632cd685/src/pages/Lend/LoanChannelCategoryControl.vue#L658

2022-10-14 16:51 UTC, roger-in-kiva commented
What about these cases?

```
Click “see # loans” CTA
ca: Lending
action: apply-quick-filters
Label: see loans

```
```
Reset countries
ca: Lending
action: Select-quick-filters-reset
Label: reset
```

2022-10-14 17:07 UTC, mcstover requested changes
Review and apply new analytics event specification.

2022-10-17 15:27 UTC, roger-in-kiva approved these changes
Seems good!

2022-10-17 15:41 UTC, merged

2022-10-17 15:52 UTC, mcstover commented on src/pages/Lend/LoanChannelCategoryControl.vue
> +				'Search',
@egoroza This line needs to be lowercased. Otherwise, thanks for getting the tracking up to date based on our new standard.