feat: activities were not shown due to lendCta being mounted before k…
kiva/ui pull request #5190
Opened 2024-03-07 22:56 UTC by christian14b

…nowing if experiment was enabled. Also, adding remaining props to kvLoanActivities

2024-03-07 23:03 UTC, roger-in-kiva requested changes
addToBasket emit is not working as expected...

2024-03-07 23:42 UTC, roger-in-kiva commented on src/components/BorrowerProfile/LendCta.vue
> +		async addToBasket(lendAmount = 0) {
Working fine from the modal but BP lend cta is broken...

2024-03-07 23:42 UTC, roger-in-kiva commented on src/components/BorrowerProfile/LendCta.vue
> +				this.errorMsg = e[0]?.extensions?.code === 'reached_anonymous_basket_limit' && e[0]?.message
We need to clean this when addToBasket method is called.

2024-03-08 00:13 UTC, roger-in-kiva approved these changes

2024-03-08 17:38 UTC, dyersituations commented on src/components/BorrowerProfile/LendCta.vue
> +			default: () => ({}),
If we are checking on whether this is defined, then this default should also be `null`

2024-03-08 17:39 UTC, dyersituations commented on src/pages/BorrowerProfile/BorrowerProfile.vue
>  			this.enableActivityFeed = true;
Can this flag be removed now that we aren't checking it?

2024-03-08 19:36 UTC, dyersituations approved these changes

2024-03-08 19:41 UTC, merged