feat: add exp tracking to users that see the deposit incentive banner
kiva/ui pull request #5295
Opened 2024-05-01 22:29 UTC by christian14b

Fire event only when banner is visible

2024-05-01 22:31 UTC, dyersituations approved these changes

2024-05-01 22:33 UTC, emuvente approved these changes

2024-05-01 22:35 UTC, emuvente requested changes
We should track it when it's not visible too. We should track whenever we have an experiment assignment

2024-05-01 23:27 UTC, dyersituations commented on src/components/WwwFrame/PromotionalBanner/GlobalPromotionalBannerContentful.vue
> +		if (version) {
Look to the usage of the `trackExperimentVersion` method.

2024-05-02 00:47 UTC, emuvente approved these changes

2024-05-02 00:48 UTC, merged